---
title: "OSLRT"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r}
library(stats)
```

```{r}
k_list <- c(0.1,0.25,0.5,1,2,5)
delta_list <- seq(1.2,2,0.1)
m0 <- 1
ta <- 3
tf <- 1
tau <- ta+tf
R_list <- 1/delta_list
alpha <- 0.05
power <- 0.9
```

##############################################################
####################  SAMPLE SIZE ############################
##############################################################

```{r}
size_ <- function(x,k,delta,R,m0,tf,ta,tau,alpha=0.05,power=0.9){
  m1 <- m0*delta^(1/k)

  Lambda0 <- function(x){log(2)*(x/m0)^k}
  Lambda1 <- function(x){log(2)*(x/m1)^k}
  Lambdabar <- function(x){0.5*(Lambda0(x) + Lambda1(x))}

  s0 <- function(x){exp(-1*Lambda0(x))}
  s1 <- function(x){exp(-1*Lambda1(x))}
  sbar <- function(x){exp(-1*Lambdabar(x))}

  lambda0 <- function(x){k*log(2)*x^(k-1)*m0^(-k)} 
  lambda1 <- function(x){k*log(2)*x^(k-1)*m1^(-k)}
  lambdabar <- function(x){0.5*(lambda0(x) + lambda1(x))}

  G <- function(x){tau-x}

  temp1 <- function(x){s1(x)*lambda0(x)}
  temp2 <- function(x){G(x)*s1(x)*lambda0(x)*ta^-1}
  p0 <- integrate(temp1,0,tf)$value + integrate(temp2,tf,tau)$value

  temp3 <- function(x){s1(x)*lambda1(x)}
  temp4 <- function(x){G(x)*s1(x)*lambda1(x)*ta^-1}
  p1 <- integrate(temp3,0,tf)$value + integrate(temp4,tf,tau)$value

  temp5 <- function(x){s1(x)*lambda0(x)*Lambda0(x)}
  temp6 <- function(x){G(x)*s1(x)*lambda0(x)*Lambda0(x)*ta^-1}
  p00 <- integrate(temp5,0,tf)$value + integrate(temp6,tf,tau)$value

  temp7 <- function(x){s1(x)*lambda0(x)*Lambda1(x)}
  temp8 <- function(x){G(x)*s1(x)*lambda0(x)*Lambda1(x)*ta^-1}
  p01 <- integrate(temp7,0,tf)$value + integrate(temp8,tf,tau)$value

  sigma0_sq <- p0
  sigma1_sq <- p1
  sigma_sq <- p1 - p1^2 + 2*p00 - p0^2 - 2*p01 + 2*p0*p1

  temp9 <- function(x){sbar(x)*lambdabar(x)}
  temp10 <- function(x){G(x)*sbar(x)*lambdabar(x)*ta^-1}
  sigmabar_sq <- integrate(temp9,0,tf)$value + integrate(temp10,tf,tau)$value
  
  omega <- sigma1_sq - sigma0_sq

  n_1 <- ((qnorm(1 - alpha)*sqrt(sigma0_sq)+qnorm(power)*sqrt(sigma_sq))^2)/(omega^2)
  n_2 <- ((qnorm(1 - alpha)*sqrt(sigma0_sq)+qnorm(power)*sqrt(sigmabar_sq))^2)/(omega^2)
  n_3 <- ((qnorm(1 - alpha)*sqrt(R)+qnorm(power)*(1/delta))^2)/(p1*((R - 1)^2))

  # ans = list("method_Wu" = n_1,"method_Jung" = n_2,"method_Finkelstein" = n_3)
  ans = list(n_1,n_2,n_3)
  return(ans)
}
```


##############################################################
####################  POWER & TYPE I ERROR   #################
##############################################################
```{r}
sample_data_0 <- function(n,k,m0,ta,tf){
  shape = k
  scale = m0/(log(2))^(1/shape)
  t = rweibull(n,shape,scale)
  u = runif(n,0,ta)
  c = as.numeric(t < ta+tf-u)
  x = pmin(t, ta+tf-u)
  data <- data.frame(time = x,cens = c)
  # data <- list("time" = t,"cens" = c)
  return(data)
}

sample_data_1 <- function(n,k,m0,ta,tf,delta){
  shape = k
  m1 = m0*delta^(1/k)
  scale = m1/(log(2))^(1/shape)
  t = rweibull(n,shape,scale)
  u = runif(n,0,ta)
  c = as.numeric(t < ta+tf-u)
  x = pmin(t, ta+tf-u)
  data <- data.frame(time = x,cens = c)
  # data <- list("time" = t,"cens" = c)
  return(data)
}

test_stat <- function(k,m0,data)
{   
  shape = k
  scale = m0/(log(2))^(1/shape)
  S=function(shape,scale,q){1-pweibull(q,shape,scale)} # null Weibull dist.
  H=function(shape,scale,u){-log(S(shape,scale,u))} # null cumu hazard function
  X=data$time   # observed failure time 
  cens=data$cens  # censoring indicate 1-event 0-censoring 
  O=sum(cens)       # observed number of events 
  M=H(shape, scale, X)
  E=sum(M)
  Z<-(E-O)/sqrt(E)
  return(Z)
}

pow_type <- function(n,k,m0,ta,tf,alpha,delta,simul_n){
  Z <- qnorm(1 - alpha)
  N <- simul_n
  s_0 <- 0
  s_1 <- 0
  for ( i in 1:N){
    data_0 <- sample_data_0(n,k,m0,ta,tf)
    data_1 <- sample_data_1(n,k,m0,ta,tf,delta)
    Z_0 <- test_stat(k,m0,data_0)
    Z_1 <- test_stat(k,m0,data_1)
    if (Z_0 > Z){
      s_0 = s_0+1
    }
    if (Z_1 > Z){
      s_1 = s_1+1
    }
  }
ans_0 = round(s_0/N,3)
ans_1 = round(s_1/N,3)
ans <- list("Power" = ans_1,"Type I error" = ans_0)
return(ans)
}


```


```{r}
my_output <- matrix(NA,nrow = 18,ncol = 28)
rownames(my_output) <- c(0.1,' ',' ',0.25,' ',' ',0.5,' ',' ',1.0,' ',' ',2.0,' ',' ',5.0,' ',' ')
colnames(my_output) <- c('formula',rep(c('n','alpha','power'),9))

my_output[,1] <- rep(c(3,2,1),6) 
```

```{r}
for (i in 1:length(k_list)){
  for (j in 1:length(delta_list)){
    temp1 <- (3*i) - 2
    temp2 <- (3*j) - 1 
    temp3 <- 3*i
    ans <- size_(x,k_list[i],delta_list[j],R_list[j],m0,tf,ta,tau,alpha=0.05,power=0.9)
    my_output[temp1:temp3,temp2] <- c(ceiling(ans[[1]]),ceiling(ans[[2]]),ceiling(ans[[3]]))
  }
}
```

```{r}
# for(j in c(2,5,8,11,14,17,20,23,26))
k_list_long <- rep(k_list,each = 3)
simul_n <- 100000

for(i in 1:18){
  for(j in 1:9){
    temp0 <- (3*j) - 1
    temp1 <- temp0 + 1
    temp2 <- temp1 + 1
    n = my_output[i,temp0]
    ans <- pow_type(n,k_list_long[i],m0,ta,tf,alpha,delta_list[j],simul_n)
    my_output[i,temp1] <- round(ans[[2]],3)
    my_output[i,temp2] <- round(ans[[1]],3)
  }
}

```

# delta = 1.2

```{r}
my_output[,c(1,2,3,4)]
```

# delta = 1.3

```{r}
my_output[,c(1,5,6,7)]
```

# delta = 1.4

```{r}
my_output[,c(1,8,9,10)]
```

# delta = 1.5

```{r}
my_output[,c(1,11,12,13)]
```

# delta = 1.6

```{r}
my_output[,c(1,14,15,16)]
```

# delta = 1.7

```{r}
my_output[,c(1,17,18,19)]
```

# delta = 1.8

```{r}
my_output[,c(1,20,21,22)]
```

# delta = 1.9

```{r}
my_output[,c(1,23,24,25)]
```

# delta = 2.0

```{r}
my_output[,c(1,26,27,28)]
```






